
GET http://localhost:3000/api/interests/17
Content-Type: application/json
Authorization: Bearer 

###
GET http://localhost:3000/api/interests/17

###
GET http://localhost:3000/api/goals/17

###
http://localhost:3000/api/availability/17

###
POST http://localhost:3000/api/users/login
Content-Type: application/json
{
    "username": "test",
    "password": "Test123"
}



###
GET http://localhost:3000/api/interests/hasInterests/10